collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2550777
color:
  saturation: 0.5191159
  brandStrength: 0
  lightness: 0.532258
  brandColors:
    - '#FFFFFF'
    - '#9EFF00'
    - '#FC4201'
    - '#FF733A'
    - '#FF9B69'
  rhythmicContrast: 0.5107526
layout_spectrum: 1
name: Maki Taco
